import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { RootState } from '../../store/store';
import { Item } from '../../types';
import { fetchItems } from './item.api';

export type Status = 'idle' | 'loading' | 'failed'

export interface ItemState {
  all: Array<Item>;
  itemsStatus: Status;
}

const initialState: ItemState = {
  all: [],
  itemsStatus: 'idle',
};

export const fetchItemsAsync = createAsyncThunk(
  'items/fetchItemsAsync',
  async (query: string) => {
    const response = await fetchItems(query);
    // The value we return becomes the `fulfilled` action payload
    return response.data.data?.items;
  }
);

export const itemsSlice = createSlice({
  name: 'items',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchItemsAsync.pending, (state) => {
        state.itemsStatus = 'loading';
      })
      .addCase(fetchItemsAsync.fulfilled, (state, action) => {
        state.itemsStatus = 'idle';
        state.all = action.payload?.slice(0, 4) as Item[];
      })
      .addCase(fetchItemsAsync.rejected, (state) => {
        state.itemsStatus = 'failed';
      });
  },
});

// export const { increment, decrement, incrementByAmount } = itemsSlice.actions;
export const selectItems = (state: RootState) => state.items.all;
export const selectItemsStatus = (state: RootState) => state.items.itemsStatus;

export default itemsSlice.reducer;
